### ISSUE TITLE
Overall assessment/review of xmlstarlet?

### ISSUE THREAD

**Issue by velle** [martin7th/xmlstarlet-notes#1]
Thanks for sharing all these notes. Its really really helpful! :)

Would you please consider also offering a kind of assessment/review of how well xmlstarlet performs overall? 

- Is it stable?
- Are some parts stable while others are not so (I read somewhere among libxml2 tickets that their XSD support is incomplete and occasioanlly buggy, so I guess xmlstarlet is too)?
- What have you used it for, and how did it do for those tasks?
- A comparison to xmllint, if you tried that out. 

I have used xmllint but have not been impressed. I would expect a tool hosted at sourceforge with no updates since 2014 to be waste of time. But now that I am finally trying it out, it seems much better than xmllint at everything I tried so far. I wonder if that is your experience too?

Best regards.

**Comment by martin7th** [comment]
This project deals with my personal notes on `xmlstarlet` so I don't really expect questions or issues here.

Questions about software recommendations are often not on topic for  the relevant StackExchange forums but [this page](https://stackoverflow.com/help/on-topic) offers a number of suggestions. And so do the answers to [this posting](https://stackoverflow.com/questions/15461737/how-to-execute-xpath-one-liners-from-shell "How to execute XPath one-liners from shell?") on StackOverflow. Perhaps you can take it from there.

**Comment by velle** [comment]
I realized that these were your personal notes, but those notes are the best documentation on xmlstarlet I found anywhere. And I know that your notes repo is not a support forum, but I thought, that perhaps you were up for making your xmlstarlet notes even more useful for the rest of the world. I hope it's ok that asked you though :) Sincerely.

**Comment by martin7th** [comment]
No problem. Glad you could make use of my notes.
